---
name: "Insomniac"
guid: "2b815d95-08e3-4fa8-ac90-8cc9e0b1cc66"
version: "1.0.0.0"
targetAbi: "10.9.0.0"
framework: "net8.0"
overview: "Insomniac Idle Inhibitor"
description: >
  Prevent system idle sleep while in active use.
category: "Other"
owner: "kanongil"
artifacts:
- "Jellyfin.Plugin.Insomniac.dll"
- "Tmds.DBus.dll"
changelog: >
  Initial release
