name: '📝 Create/Update Release Draft & Release Bump PR'

on:
  push:
    branches:
      - main
    paths-ignore:
      - build.yaml
  workflow_dispatch:
  repository_dispatch:
    types:
      - update-prep-command

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/changelog.yaml@bf066268236cea6d28519d477ba225ee3c635707
    with:
      repository-name: kanongil/jellyfin-plugin-insomniac
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
