name: '🏷️ Sync labels'

on:
  schedule:
    - cron: '0 0 1 * *'
  workflow_dispatch:

jobs:
  call:
    uses: jellyfin/jellyfin-meta-plugins/.github/workflows/sync-labels.yaml@bf066268236cea6d28519d477ba225ee3c635707
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}
